[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"


[env]
ESP_LOGLEVEL="DEBUG"
[build]
rustflags = [
  # GNU LD
  # "-C", "link-arg=-nostartfiles",
  # "-C", "link-arg=-Wl,-Tlinkall.x",

  # LLD
  "-C", "linker=rust-lld",
  "-C", "link-arg=-Tlinkall.x",

  "-C", "save-temps", # helpful for keeping all .o's around to relink without a full build
  "-C", "link-arg=--threads=1" # single threaded lld for clean prints
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
